!scr "", 0x22 ,"trap them music", 0x22 ," by spider / myd! in memory of vernunftmensch. additional "
!scr "graphics by retrofan. original graphics by j-snake. code, music and font by "
!scr "spider. "
!scr "this is a collection of all the music i made for vernunftmensch while he was "
!scr "working on his c64 port of ", 0x22 ,"trap them", 0x22 ,". i must admit i don't know which versions "
!scr "of the tunes he managed to build into the last version and which not. but these "
!scr "are the final versions of all songs that i sent to him. all tunes except "
!scr "", 0x22 ,"introduction", 0x22 ," are 2 sid voices only, because the third sid voice was "
!scr "reserved for sfx. there were two songs that i named for this collection that "
!scr "were only named ", 0x22 ,"owntune01", 0x22 ," and ", 0x22 ,"owntune02", 0x22 ," before, because the other ones "
!scr "had the original soundtrack of the pc version as template. this whole project "
!scr "was kind of super crazy and often times all the sceners who participated "
!scr "in helping vernunftmensch lost their minds over the kind of strange ideas "
!scr "he had for this project. but he was really passionate about it and kept on "
!scr "going against all odds. i remember one time finally meeting him at a bunker "
!scr "party and he was such a nice guy and it was a pleasure to spend time with him. "
!scr "and it's often the case when we ", 0x22 ,"meet", 0x22 ," people online that we forget that "
!scr "there is a complete human being behind our online ", 0x22 ,"personas", 0x22 ,". and yeah, "
!scr "people called me out for being a ", 0x22 ,"materialist", 0x22 ," - but for me it's really "
!scr "something special to meet folks i only know from the internet in the rl aka "
!scr "real life. i'm glad that i had the opportunity to meet vernunftmensch. "
!scr "everything about his passion that may have looked silly from the distance of "
!scr "the internet wasn't that silly anymore when meeting him. he lived his dream. "
!scr "he wanted to port this game to c64 and he did everything in his power to "
!scr "do so. for that he has earned my honest respect. and if there is a heaven "
!scr "and if there is a god i'm really looking forward to meet vernunftmensch again "
!scr "in the golden city of new jerusalem. and if not: he left a lasting impression "
!scr "on me - of someone who is really dedicated to one thing. and i'll keep that "
!scr "impression as a treasure in my heart as long as i live. thank you helmut! "
!scr "i am happy that i could contribute a little part to your dream! "
